// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAddTFMhCjy0wHsjxvkqDFvAN3WDQJ6ueA',
    appId: '1:1078947515781:web:93b84ebd3a114aa76808ec',
    messagingSenderId: '1078947515781',
    projectId: 'seangkatanmvp',
    authDomain: 'seangkatanmvp.firebaseapp.com',
    storageBucket: 'seangkatanmvp.firebasestorage.app',
    measurementId: 'G-SVEWD1X2WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3wDwheCIBf4y2THg63BNjn3ivCGrI1w',
    appId: '1:1078947515781:android:54dab6397d49f2c56808ec',
    messagingSenderId: '1078947515781',
    projectId: 'seangkatanmvp',
    storageBucket: 'seangkatanmvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUB7I7LKcXtmuVBbGhgRiTbVAh0y3lv3E',
    appId: '1:1078947515781:ios:81118d70f2a27b9b6808ec',
    messagingSenderId: '1078947515781',
    projectId: 'seangkatanmvp',
    storageBucket: 'seangkatanmvp.firebasestorage.app',
    iosBundleId: 'com.seangkatan.sekolahapps.sekangkatanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUB7I7LKcXtmuVBbGhgRiTbVAh0y3lv3E',
    appId: '1:1078947515781:ios:81118d70f2a27b9b6808ec',
    messagingSenderId: '1078947515781',
    projectId: 'seangkatanmvp',
    storageBucket: 'seangkatanmvp.firebasestorage.app',
    iosBundleId: 'com.seangkatan.sekolahapps.sekangkatanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAddTFMhCjy0wHsjxvkqDFvAN3WDQJ6ueA',
    appId: '1:1078947515781:web:0920071413fa5bc26808ec',
    messagingSenderId: '1078947515781',
    projectId: 'seangkatanmvp',
    authDomain: 'seangkatanmvp.firebaseapp.com',
    storageBucket: 'seangkatanmvp.firebasestorage.app',
    measurementId: 'G-3PGD5LF5FT',
  );
}
